### ISSUE TITLE
Docker-Compose

### ISSUE THREAD

**Issue by TorbenHaug** [Transport-Protocol/MBC-Ping-Pong#10]
# Beschreibung:
Mittels docker-compose ist es möglich Dockercontainter zu managen. Dazu werden die entsprechenden Dockercommands in einer Yaml-Datei gespeichert.

# Anforderung:
Der Dockercontainer soll möglichst einfach zu starten sein.

# Abnahmekriterien:
 - `docker-compose up` startet den Container und gibt den Port 8080 auf dem Hostsystem frei.
 - `docker-compose build` erstellt den Container

**Comment by AndreasMue** [comment]
@TorbenHaug 
Auf meinem Laptop unter Linux getestet: Lauffähig.
Test auf Windows steht noch aus, kommt nachher.

**Comment by AndreasMue** [comment]
@TorbenHaug Bei mir funktioniert es auf verschiedenen Computern einwandfrei.
