### ISSUE TITLE
Analyse - Steuerung

### ISSUE THREAD

**Issue by TorbenHaug** [Transport-Protocol/MBC-Ping-Pong#11]
# Beschreibung:
Die Steuerung des Spiels erfolgt über das Handydisplay. Jedes Handy ist unterschiedlich groß, zudem sollte der Schläger nicht springen können.

# Anforderung
Es ist ein Konzept, auf Basis der in #4 abgegriffenen Koordinaten, zu entwickeln, das möglichst fair die Steuerung des Schlägers auf allen Handys und Tabletts erlaubt.

# Abnahmekriterien:
- Es wird beschrieben, wie mit den Unterschiedlichen Handygrößen umgegangen wird.
- Es wird beschrieben, wie eine flüssige Bewegung garantiert wird.
  - Der Schläger darf nicht durch die einfache Berührung des Bildschirms eine Spezielle Position einnehmen können.

**Comment by Blackgen** [comment]
Bin auf etwas sehr interessantes gestoßen das uns weiterhelfen kann:
'window.devicePixelRatio'
http://www.quirksmode.org/blog/archives/2012/06/devicepixelrati.html
http://www.quirksmode.org/blog/archives/2012/07/more_about_devi.html

'window.devicePixelRatio' ist ein verhältnis zwischen den Physikalischen Pixeln und den device indipendent Pixels (dips)
Wird vor allem genutzt um Webinhalte, speziell Texte, auf verschiedenen displaygrößen einheitlich darzustellen.

**Comment by Blackgen** [comment]
Kurzer Test:
https://jsfiddle.net/jwzkcy7e/1/
Zeigt ein Quadrat, dieses ist auf vielen Geräten annähernd gleich groß.
Auf meinem PC ist es 100px bzw 2.7 cm
Auf meinem Handy 300px bzw 1.9cm

Weiß nicht ob ich viel näher dran komme.
Werte von verschiedenen Mobilgeräten wären interessant

**Comment by Blackgen** [comment]
Zu den Daten der Steuerung.
Wir brauchen eigentlich nur einen Wert
Beispielsweise:
{delta:100}

Der Y wert ist für uns nicht von Interesse weil der Schläger sich nicht frei im Raum bewegen soll (Oder??)
Wenn wir Irgendwann auf mehrere Spieler gehen dann bekommen die Schläger bei der Erstellung eine Richtung zugewiesen. So brauchen sie weiterhin nur eine Veränderung der Position auf ihrer Achse (Auch wenn diese Achse in ihrer Richtung gedreht ist)

**Comment by TorbenHaug** [comment]
Zunächst hast du recht, ich würde trotzdem gleich x und y übertragen und die Filterung beim DisplayPeer vornehmen. Der Hintergrund ist der, das die Implementierung mit x und y nicht wesentlich aufwändiger ist, als nur x zu übertragen. Eine spätere Änderung würde sich aber durch die gesamte Anwendung ziehen, und ist somit sehr komplex.

**Comment by TorbenHaug** [comment]
Alternativ kann man über ein kommuliertes Delta nachdenken. Also delta=wurzel(diff(x)²+diff(y)²).

**Comment by Blackgen** [comment]
#19
