### ISSUE TITLE
Dokumentation - Risiken

### ISSUE THREAD

**Issue by TorbenHaug** [Transport-Protocol/MBC-Ping-Pong#12]
# Beschreibung:
Um Risiken begegnen zu können muss man sie kennen. Auch in kleinen Projekten gibt es Risiken und Risiken, die in einem größeren Projekt vll. so extrem sind, können in einem kleinen Team bereits verheerende Auswirkungen haben.

# Anforderung:
Es sind möglichst viele Risiken (alle ist unmöglich) zu ermitteln, zu Beschreiben, die Eintrittswahrscheinlichkeit (1:Gering, 2:Mittel, 3: Hoch) zu ermitteln, den entstehenden Schaden zu beziffern( 1:Gering, 2:Mittel, 3: Hoch) und eine Strategie zu nennen, wie mit dem Risiko umgegangen wird. 

# Abnahmekriterien:
- Es sind alle Risiken eingestuft
- Die Risiken sind verständlich beschrieben
- Es sind keine weiteren Risiken von den Teammitglieder mehr hinzuzufügen

**Comment by AndreasMue** [comment]
@TorbenHaug Bei allen Risiken stimme ich so vollkommen zu, jedoch würde ich persönlich die Auswirkungen bei den beiden Risiken bezüglich Personalausfall einen Punkt höher setzen. (Am liebsten einen halben Punkt ;) )
Ansonsten, klasse Auflistung!

**Comment by TorbenHaug** [comment]
Präsentiert und geschlossen
