### ISSUE TITLE
WebRTC technischer Durchstich

### ISSUE THREAD

**Issue by TorbenHaug** [Transport-Protocol/MBC-Ping-Pong#2]
# Beschreibung:
Um eine reibungsfreie Übertragung der Positionsdaten des Fingers an die Spiellogik zu gewährleisten, ist eine direkte Kommunikation des Anzeigegeräts (Browser auf dem Präsentierenden Rechners) und dem Handy des Spielers notwendig. Hierfür ist die Nutzung des WebRTC Protokollstacks notwendig. 

# Anforderung:
In diesem ersten Schritt ist zu zeigen, dass eine direkte Kommunikation zwischen Anzeigegeräts und Handy, unter Verwendung des NodeJS Servers als Vermittlers funktioniert.

# Abnahmekriterien:
 - Aufruf der Seite http://\<IpDesNodeJsServers\>:\<HttpPortDesNodeJsServers\>/testWebRTC.html zeigt die Testseite
 - Eine URL zur Eingabe in das Handy ist zu sehen
 - Die URL kann in eine Browser auf dem Handy eingegeben werden
 - Auf dem Handy wird eine zufällige Zahl generiert, angezeigt und an das Anzeigegerät gesendet
 - Anzeigegerät gibt die empfangene Zahl auf der Console aus

**Comment by AndreasMue** [comment]
http://www.avaya.com/blogs/archives/2014/08/understanding-webrtc-media-connections-ice-stun-and-turn.html  
https://www.w3.org/TR/webrtc/images/ladder-2party-simple.svg
