### ISSUE TITLE
DisplayPeer - Schläger

### ISSUE THREAD

**Issue by TorbenHaug** [Transport-Protocol/MBC-Ping-Pong#22]
# Beschreibung:
Der Schläger ist ein Elementares Element des Spieles. in #11 wurde ein Konzept entwickelt, in welchem 
festgelegt wurde, welche Daten an den Schläger übermittelt werden. <br>
Es werden X- und Y-Diffs zum Spiel übertragen. Diese werden dem Player mittels addPositionToBuffer(x,y) mitgeteilt.

# Anforderungen:
Es können maximal 2 Spieler erstellt werden. Der erste Spieler erhält den Schläger auf der linken Seite, der zweite Spieler den auf der rechten Seite. Die Schläger sind auf ihrer X-Position fixiert. Die Positionsänderungen für die Y-Achse, die im Buffer sind, werden kumuliert und auf den Schläger angewendet. Der Schläger darf sich dadurch jedoch nicht aus dem Spielfeld (begrenzt durch die Wände in #26 ) herausbewegen. 

# Abnahmekriterien:
* Es können maximal 2 Spieler erstellt werden
* Der erste Spieler ist Links, der zweite Spieler ist Rechts
* ~~Die Schläger verhalten sich, wie in den Anforderungen beschrieben~~ will be done in #25

**Comment by Blackgen** [comment]
Aktueller Stand spiegelt die Anforderungen wieder bis auf:
* Mehr Player können sich verbinden, es werden aber nur 2 Sprites verteilt
* Der Input vom Handy ist noch immer Absolut, nicht relativ. Da die Controller das noch nicht hergeben

**Comment by Blackgen** [comment]
Steuerung fehlt um hier weiter zu machen
# Blocked by: #25

**Comment by TorbenHaug** [comment]
Nach Rücksprache Rücksprache​ mit @Shivon wird die Anpassung an die relative Bewegung in #25 gemacht. Dies entfällt entsprechend in diesem Issue.

**Comment by Blackgen** [comment]
Nach dem Wechsel der Physic Engine passen die Schläger nicht mehr. 
Das muss ich auch noch machen. 
Also sowohl Endpunkte als auch ABstand zum Bildschirmrand
