### ISSUE TITLE
WebRTC

### ISSUE THREAD

**Issue by TorbenHaug** [Transport-Protocol/MBC-Ping-Pong#23]
# Beschreibung:
Während #16 wurde festgestellt, das die gewählte WebRTC-Implementierung fehlerhaft ist. Daher ist eine spezialisierte Eigenimplementierung der sinnvollste logisch nächste Schritt. Diese Eigenentwicklung soll auf Socket.IO für die Websockets basieren.

# Anforderungen:
Es sollten mehrer Peers mit einem Peer und ein Peer mit mehreren Peers (aber 1 zu 1) kommunizieren können. Als Vermittler dient ein NodeJS-Server

# Abnahmekriterien:
* Es können sich n DisplayPeers sich beim Server anmelden
* Es konnen sich n ControlPeers beim Server anmelden (jeder ControlPeer gehört zu einem DisplayPeer)
* Meldet sich ein ControlPeer beim Server an, wird dieser seinem DisplayPeer zugewiesen
* Ist die Zuweisung beendet, findet die Kommunikation zwischen Display- und ControlPeer direkt statt
* Tritt ein Fehler während des Verbindens auf,  wird der auslösende Client disconnected.

**Comment by TorbenHaug** [comment]
Eine Vorabversion ist im Master.
Diese funktioniert jedoch nur korrekt mit dem Chrome Browser.

Firefox Fehler:
* Das Disconnect-Event wird erst ausgelößt, wenn der Browser geschlossen wird. Es sollte aber auch ausgelöst werden, wenn die Seite aktualisiert, bzw. verlassen wird.

Allgemeine Fehler:
* Wird der DisplayPeer geschlossen und erneut geöffnet, erscheint folgende Fehlermeldung: Multi-Peer tried to join room with another Multi-Peer
* Wird ein zweiter DisplayPeer geöffnet, gibt es keine Möglichkeit sich mit diesem zu verbinden

**Comment by AndreasMue** [comment]
Bezüglich Firefox Fehler: 

- Bei mir kam das Disconnect-Event beim schließen des Tabs (inkl. Verzögerung von ca 4 Sekunden). Ein paar Logs (aus der Konsole des Display-Peer) wären hier jetzt hilfreich.

- Sofern der Fehler genau so auftritt ist das wieder ein Verstoß der Firefox spezifischen Implementation von WebRTC und muss auf unserer Seite dann anders gelöst werden.

Bezüglich Allgemeine Fehler:

- Beide Fehler basieren noch auf dem nicht Nutzen einer GameID. Wird direkt nach dem Merge von #29 behoben.
