### ISSUE TITLE
DisplayPeer - InitialState

### ISSUE THREAD

**Issue by TorbenHaug** [Transport-Protocol/MBC-Ping-Pong#26]
# Beschreibung:
Der Initiale Zustand wird dargestellt, wenn die Seite geladen wird.

# Anforderungen:
Der initiale Zustand soll gemäß der Mockups aus #24 dargestellt werden. 
![initial state](https://rawgit.com/Transport-Protocol/MBC-Ping-Pong/master/docu/maindocumentation/architecture/Mookup%20-%20Initial.png)
Achtung grüne Texte dienen nur der Beschriftung.

# Abnahmekriterien:
* Die Wände werden angezeigt.
* Die Punkte werden angezeigt.
* Der Ball wird angezeigt, bewegt sich jedoch nicht.
* Das LoinGamePanel wird angezeigt
 * Die URL1 setzt sich wie folgt zusammen: <momentane url ohne "\/DisplayPeer.html">\/ControlPeer.html (zunächst ohne id)
  * http:\/\/test.bsp\/DisplayPeer.html => http:\/\/test.bsp\/ControlPeer.html 
  * https:\/\/example.bsp\/DisplayPeer.html => https:\/\/example.bsp\/ControlPeer.html 
 * Der QR-Code wird aus der URL1 generiert

**Comment by Blackgen** [comment]
Die Wände links und rechts können entfallen. 
Die Flächen hinter den Schlägern stellen Tore da, und für den Spieler sollte erkennbar sein das der Ball verloren geht wenn er ihn nicht mit dem Schläger trifft.
Alternativ könnte man diese Wände Rot färben

**Comment by TorbenHaug** [comment]
Einfärben gerne, aber ich finde die Abtrennung mit den Wänden ganz schön. Zudem ist das programmtechnisch später gut, da man dann ein Objekt hat, mit dem der Ball kollidiert.

**Comment by Blackgen** [comment]
Hab ein erstes Problem festgestellt.
Das Spiel kommt mit unseren Objekten nicht direkt klar.
Beispielsweise bei der Kollisionsprüfung.
Da werden anscheinend nur die von "Game.add.sprite" erzeugten Objekte angenommen

Hab alle Wände in eine Gruppe aufgenommen und versucht Kollisionen abzufragen, es passiert nichts. Mit normalen Objekten klappt die abfrage

**Comment by Blackgen** [comment]
Relevant: [Commit, Bekannte Probleme](https://github.com/Transport-Protocol/MBC-Ping-Pong/commit/95ea12b1cc750199c21e86db8c3fd7d62075ea0c#commitcomment-20316616)

**Comment by TorbenHaug** [comment]
Die Kollisionserkennung mit der Wand3 funktioniert nun. <br />
Mit Wand1 und Wand2 nicht (vgl.: https://github.com/photonstorm/phaser/issues/752).<br />

Lösungsvorschläge:
1. Ein Spritesheet mit 360 Bildern (eines pro Grad)
2. Umsteigen auf P2JS (könnte performance Probleme geben).

**Comment by TorbenHaug** [comment]
Zu Lösungsvorschlag 1:
Ich habe nicht bedacht, dass das angeben einer Höhe oder Breite, bei gedrehten Bilder nicht zum gewünschten Ergebnis führt. Daher langt es, dass zunächst 2 Bilder genutzt werden: Eines Horizontal, das andere Vertikal. Diese können dann auch bereits in der richtigen Größe vorliegen.
Sollten später anders geformte Spielfelder erstellt werden sollen, müssen entsprechende weitere Sprites erstellt werden.

**Comment by Blackgen** [comment]
AH mist ich war davon ausgegangen das es klappt auch bei gedrehten Bildern
Wie ist das dann mit gestreckten Bildern? 
Das könnte auch bedeuten das die Kollision mit gedrehten Wänden ganz und gar nicht klappt

**Comment by Blackgen** [comment]
Arcade Physics uses an AABB (axis-aligned, bounding box) collision system only. 
Das bedeutet wir können schräge wände nicht erkennen
Damit ist der 3 Spieler modus gestorben


Edit: Versuche auf die P2 Physic Engine umzuschwenken

**Comment by TorbenHaug** [comment]
@Shivon please review
