### ISSUE TITLE
Auswahl einer geeigneten 2D-/Physiksengine

### ISSUE THREAD

**Issue by TorbenHaug** [Transport-Protocol/MBC-Ping-Pong#3]
# Beschreibung:
Die Darstellung auf dem Anzeigegerät ist über den DOM nicht möglich, da die Bewegung des Balls und der Schläger zu schnell werden. Zudem wird auch die Physik auf dem Anzeigegeräts berechnet. Hierfür ist eine Kollisionserkennung erforderlich.

# Anforderung:
In diesem ersten Schritt ist eine entsprechende Library auszuwählen und die Funktionalität zu demonstrieren.

# Abnahmekriterien:
- Aufruf der Seite http://\<IpDesNodeJsServers\>:\<HttpPortDesNodeJsServers\>/test2DEngine.html zeigt die Testseite.
- Ein quadratischer Bereich mit einer Form in der Mitte auf dem Bildschirm wird dargestellt.
- In diesem Bereich bewegt sich eine Form (am besten eine Kugel) waagerecht von Links nach Rechts.
- Kollidiert die Form mit der rechten Wand, bewegt sich die Form von Rechts nach Links.
- Kollidiert die Form mit der linken Wand, bewegt sich die Form von Links nach Rechts.

**Comment by Blackgen** [comment]
Ich hatte mir bisher diese hier angeguckt:
http://brm.io/matter-js/

**Comment by Shivon** [comment]
Phaser wäre meine Empfehlung, viele Demos inkl Code und eins davon ist eigentlich schon so ziemlich das, was wir wollen: http://phaser.io/examples/v2/arcade-physics/bounce-knock

**Comment by Blackgen** [comment]
Die Engine sieht einfacher aus. Vor allem scheint es brauchbare Beispiele zu geben..
Weißt du wie das mit den Hitboxen bei Phaser funktioniert? Sind die exact wie der Sprite oder Box förmig?

Für ein 3-Spieler spiel müssten wir die Begrenzungen Schräg setzen, denkst du das lässt sich gut damit machen?

**Comment by Shivon** [comment]
Scheint so wie die Sprites zu sein, müsste ich aber nochmal verifizieren

**Comment by Blackgen** [comment]
#13 Fertiger Prototyp für den Engine-test

**Comment by TorbenHaug** [comment]
@Blackgen Die Implementierung ist gut. 
@Shivon Bitte die Analyse nachreichen.
