### ISSUE TITLE
Positionserfassung des Fingers auf dem Handy

### ISSUE THREAD

**Issue by TorbenHaug** [Transport-Protocol/MBC-Ping-Pong#4]
# Beschreibung:
Die Steuerung der Schläger soll über ein Handy oder Tablett erfolgen. Hierfür wird eine Website auf dem Handy aufgerufen. Auf dieser kann der Nutzer durch wischen mit dem Finger über den Handybiĺdschirm den Schläger auf dem Anzeigegerät steuern.

# Anforderung:
In diesem ersten Schritt ist zu demonstrieren, das die Positionsdaten des Fingers auf dem Bildschirm des Handys erfasst und verarbeitet werden kann.

# Abnahmekriterien:
- Aufruf der Seite http://\<IpDesNodeJsServers\>:\<HttpPortDesNodeJsServers\>/testSwype.html zeigt die Testseite.
- Oben links wird die Position des Fingers auf dem Bildschirm (Initial: Undefined:Undefined)
- Bei der Berührung mit dem Finger des Bildschirms, wird die Position entsprechend Aktualisiert.
- Wenn der Finger Bewegt wird, wird die Position intervallabhängig aktualisiert.

**Comment by Shivon** [comment]
Guter Artikel: https://www.html5rocks.com/en/mobile/touchandmouse/
Tendenziell sollte man das wohl über die browserspezifischen APIs machen und keine Lib, aber es gibt Libs. Wie gut die sind, muss noch verglichen werden.

**Comment by TorbenHaug** [comment]
Aus Zeitgründen, und weil benötigte Komponenten (Browserify) nur in dem Branch TechnicalDemonstrator vorhanden sind, wird dieses Issue nicht auf einem eigenen Branch bearbeitet.

**Comment by TorbenHaug** [comment]
Um bereits den Anforderungen des TechnicalDemonstrators gerecht zu werden, ist die Seite nicht unter http://\<IpDesNodeJsServers\>:\<HttpPortDesNodeJsServers\>/testSwype.html erreichbar, sondern unter http://\<IpDesNodeJsServers\>:\<HttpPortDesNodeJsServers\>/ControlPeer.html

**Comment by TorbenHaug** [comment]
Um den Stand für das Review einzufrieren, wurde ein Branch #4_FingerPositionHandler erstellt.
Wenn das Review OK ist, und keine Änderungen mehr gemacht werden müssen, kann der Branch direkt gelöscht werden. Der Merge in den Master geschieht dann mit #16.
