### ISSUE TITLE
Initiale Dokumentation

### ISSUE THREAD

**Issue by TorbenHaug** [Transport-Protocol/MBC-Ping-Pong#5]
# Beschreibung:
Um die Dokumentation einheitlich und versionierbar zu machen, wurde beschlossen, diese in Latex zu erstellen und im Ordner Docu in das Repo mit einzuchecken.

# Anforderung:
Ein Latex Projekt auf Basis des HAW-Layouts wird erstellt. Jedes Projektmitglied bekommt ein Chapter. Es wird Dokumentiert, wie unter Ubuntu ein PDF aus aus den Files erstellt werden kann.

# Abnahmekriterien:
- Projekt erstellt
- Tex File für jeden Bereich
- README.md mit Beschreibung für das Kompilieren.

**Comment by AndreasMue** [comment]
@TorbenHaug Alle Kriterien sind erfüllt worden.
