### ISSUE TITLE
Architektur Dokumentation - Highlevel View

### ISSUE THREAD

**Issue by TorbenHaug** [Transport-Protocol/MBC-Ping-Pong#8]
# Beschreibung:
Um ein gemeinsames Architektur- und Vokabularverständnis zu erreichen, ist eine Highlevel View nötig.

# Anforderung:
Es soll der allgemeine Aufbau gezeigt, benamt und beschrieben werden. Es sollen die allgemeinen Kommunikationswege gezeigt, benamt und beschrieben werden. Es soll die allgemeine Funktion der einzelnen Konten beschrieben werden.

# Abnahmekriterien:
- Der allgemeine Aufbau ist vorhanden und verständlich beschrieben und bebildert, außerdem wahrscheinlich korrekt.
- Die allgemeinen Kommunikationswege sind vorhanden und verständlich beschrieben und bebildert, außerdem wahrscheinlich korrekt.
- Die allgemeine Funktion ist vorhanden und verständlich beschrieben und bebildert, außerdem wahrscheinlich korrekt.

**Comment by AndreasMue** [comment]
@TorbenHaug Highlevel View scheint korrekt. Von meiner Seite aus alles in Ordnung.
