### ISSUE TITLE
Architektur Dokumentation -  Initiale Milestones

### ISSUE THREAD

**Issue by TorbenHaug** [Transport-Protocol/MBC-Ping-Pong#9]
# Beschreibung:
Um einen gemeinsamen Zeitplan zu gewährleisten, müssen Milestones definiert werden. Dies wurden am Fr. den 25.11.16 diskutiert und die Ergebnisse in [Milestones.pdf](https://github.com/Transport-Protocol/MBC-Ping-Pong/blob/03fb5e0e4ac73a7a5f82ad2be770339f3c326879/docu/Milestones.pdf) festgehalten.

# Anforderung:
Die Besprochenen Milestones werden ausformuliert und detailliert.

# Abnahmekriterien:
- Die Milestones sind verständlich und vollständig (wie Besprochen formuliert).

**Comment by AndreasMue** [comment]
@TorbenHaug Die Milestones sind alle vorhanden und verständlich ausformuliert.
